service: bonfire
image: leomorpho/bonfire

servers:
  - 5.78.67.78

registry:
  server: ghcr.io
  username: leomorpho
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - TURSO_DB_AUTH_TOKEN
    - TURSO_DB_URL
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - RESEND_SERVER_TOKEN
    - PUBLIC_FROM_EMAIL
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - DEV_STRIPE_SECRET_KEY
    - DEV_STRIPE_WEBHOOK_SECRET
    - SIGNIN_IP_RATELIMIT
    - PUBLIC_PROJECT_NAME
    - PUBLIC_ORIGIN
    - PUBLIC_DEFAULT_TITLE
    - PUBLIC_DEFAULT_DESCRIPTION
    - PUBLIC_TRIPLIT_URL
    - PUBLIC_TRIPLIT_ANONYMOUS_TOKEN
    - TRIPLIT_SERVICE_TOKEN
    - EXTERNAL_JWT_SECRET
    - S3_REGION
    - S3_ENDPOINT
    - DEV_S3_BUCKET_NAME
    - DEV_S3_ACCESS_KEY_ID
    - DEV_S3_SECRET_ACCESS_KEY
    - S3_BUCKET_NAME
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - PUBLIC_S3_BONFIRE_PUCLIC_BUCKET_NAME
    - S3_BONFIRE_PUBLIC_ACCESS_KEY_ID
    - S3_BONFIRE_PUBLIC_SECRET_ACCESS_KEY
    - PUBLIC_DEV_VAPID_PUBLIC_KEY
    - DEV_VAPID_PRIVATE_KEY
    - PUBLIC_VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - HERE_GEOCODING_APP_ID
    - HERE_GEOCODING_APP_KEY
    - GOOGLE_GEOCODING_API_KEY
    - SPLITWISE_CONSUMER_KEY
    - SPLITWISE_CONSUMER_SECRET
    - BODY_SIZE_LIMIT

proxy:
  app_port: 3000
  ssl: true
  host: bnfr-events.app
  forward_headers: true
  buffering:
    requests: false
    responses: false

volumes:
  - "/mnt/data/uploads:/app/uploads"
