name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Create .env file from GitHub Secrets
      - name: Create .env file
        if: ${{ secrets.ENV_FILE && secrets.ENV_FILE != '' }}
        run: echo "${{ secrets.ENV_FILE }}" > .env
        shell: bash

      # Start Docker services
      - name: Start services with docker-compose
        run: |
          docker-compose up -d
        # Wait for the services to be ready
      - name: Wait for services to be ready
        run: sleep 30 # Adjust based on your service startup time

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: pnpm exec playwright test

      # Upload Playwright report
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Tear down Docker services
      - name: Stop Docker services
        if: always()
        run: docker-compose down
